name: Test compilation

on:
  push:
    branches:
      - iris-wasm-opam
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-iris-wasm.opam'
        coq_version:
          - '8.13.2'
        ocaml_version:
          - '4.14.0-flambda'
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: ${{ matrix.opam_file }}
          coq_version: ${{ matrix.coq_version }}

          before_install: |
            startGroup "install dependencies"
              sudo apt update
              sudo apt install nano --yes

              sudo chmod 777 ~/. -R
              sudo chmod 777 . -R
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
